import type { Customer, Invoice, Quote, Summary } from "../api/types";

// Lightweight, dependency-free PDF export: render a clean print document in a
// hidden iframe and trigger the browser's print dialog, where the user can
// "Save as PDF". Works offline and adds no bundle weight.

const GST_RATE = 0.1;

function money(n: number): string {
  return `$${n.toFixed(2)}`;
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c] as string,
  );
}

const STYLE = `
  * { box-sizing: border-box; }
  body { font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
         color: #1f2937; margin: 0; padding: 48px; font-size: 13px; }
  .head { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 32px; }
  .brand { font-size: 22px; font-weight: 800; }
  .brand span { color: #7c3aed; }
  .doc-title { text-align: right; }
  .doc-title h1 { margin: 0; font-size: 24px; letter-spacing: 1px; text-transform: uppercase; color: #111827; }
  .doc-title .ref { color: #6b7280; font-family: ui-monospace, monospace; margin-top: 4px; }
  .meta { display: flex; justify-content: space-between; gap: 24px; margin-bottom: 28px; }
  .meta h3 { font-size: 11px; text-transform: uppercase; letter-spacing: .5px; color: #9ca3af; margin: 0 0 6px; }
  .meta p { margin: 2px 0; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; }
  th { text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: .5px;
       color: #9ca3af; border-bottom: 2px solid #e5e7eb; padding: 8px 6px; }
  td { padding: 9px 6px; border-bottom: 1px solid #f3f4f6; }
  .right { text-align: right; }
  .totals { margin-top: 18px; margin-left: auto; width: 280px; }
  .totals .row { display: flex; justify-content: space-between; padding: 5px 6px; }
  .totals .grand { border-top: 2px solid #e5e7eb; margin-top: 6px; font-weight: 800; font-size: 16px; color: #111827; }
  .status { display: inline-block; padding: 3px 10px; border-radius: 999px; font-size: 11px;
            font-weight: 600; background: #ede9fe; color: #6d28d9; }
  .notes { margin-top: 28px; color: #4b5563; }
  .foot { margin-top: 44px; padding-top: 14px; border-top: 1px solid #e5e7eb;
          color: #9ca3af; font-size: 11px; text-align: center; }
`;

function printHtml(title: string, body: string): void {
  const doc = `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(
    title,
  )}</title><style>${STYLE}</style></head><body>${body}<div class="foot">Generated by TradeDesk · ${new Date().toLocaleDateString()}</div></body></html>`;

  const iframe = document.createElement("iframe");
  iframe.style.position = "fixed";
  iframe.style.right = "0";
  iframe.style.bottom = "0";
  iframe.style.width = "0";
  iframe.style.height = "0";
  iframe.style.border = "0";
  document.body.appendChild(iframe);

  const win = iframe.contentWindow;
  const idoc = iframe.contentDocument || win?.document;
  if (!idoc || !win) {
    document.body.removeChild(iframe);
    return;
  }
  idoc.open();
  idoc.write(doc);
  idoc.close();

  // Give the iframe a tick to lay out before printing, then clean up.
  win.focus();
  setTimeout(() => {
    win.print();
    setTimeout(() => document.body.removeChild(iframe), 1000);
  }, 250);
}

const brand = `<div class="brand">Trade<span>Desk</span></div>`;

export function exportInvoicePdf(inv: Invoice, customer?: Customer): void {
  // Stored invoice amount is ex-GST; show GST + total for a complete document.
  const gst = +(inv.amount * GST_RATE).toFixed(2);
  const total = +(inv.amount + gst).toFixed(2);
  const cust = customer
    ? `<p><strong>${escapeHtml(customer.name)}</strong></p>
       ${customer.contact ? `<p>${escapeHtml(customer.contact)}</p>` : ""}
       ${customer.email ? `<p>${escapeHtml(customer.email)}</p>` : ""}
       ${customer.phone ? `<p>${escapeHtml(customer.phone)}</p>` : ""}
       ${customer.site_address ? `<p>${escapeHtml(customer.site_address)}</p>` : ""}`
    : `<p><strong>${escapeHtml(inv.customer)}</strong></p>`;

  const body = `
    <div class="head">${brand}
      <div class="doc-title"><h1>Invoice</h1><div class="ref">${escapeHtml(inv.id)}</div></div>
    </div>
    <div class="meta">
      <div><h3>Bill to</h3>${cust}</div>
      <div class="right">
        <h3>Details</h3>
        <p>Issued: ${escapeHtml(inv.issued_date ?? "—")}</p>
        <p>Due: ${escapeHtml(inv.due_date ?? "—")}</p>
        ${inv.job_id ? `<p>Job: ${escapeHtml(inv.job_id)}</p>` : ""}
        <p>Status: <span class="status">${escapeHtml(inv.status)}</span></p>
      </div>
    </div>
    <table>
      <thead><tr><th>Description</th><th class="right">Amount</th></tr></thead>
      <tbody>
        <tr><td>Services rendered${inv.job_id ? ` (${escapeHtml(inv.job_id)})` : ""}</td>
            <td class="right">${money(inv.amount)}</td></tr>
      </tbody>
    </table>
    <div class="totals">
      <div class="row"><span>Subtotal (ex GST)</span><span>${money(inv.amount)}</span></div>
      <div class="row"><span>GST (10%)</span><span>${money(gst)}</span></div>
      <div class="row grand"><span>Total</span><span>${money(total)}</span></div>
    </div>`;
  printHtml(`Invoice ${inv.id}`, body);
}

export function exportQuotePdf(q: Quote): void {
  const rows = q.line_items
    .map(
      (li) => `<tr>
        <td>${escapeHtml(li.description)}</td>
        <td class="right">${li.qty}</td>
        <td class="right">${money(li.unit_price)}</td>
        <td class="right">${money(li.qty * li.unit_price)}</td>
      </tr>`,
    )
    .join("");

  const body = `
    <div class="head">${brand}
      <div class="doc-title"><h1>Quote</h1><div class="ref">${escapeHtml(q.id)}</div></div>
    </div>
    <div class="meta">
      <div><h3>Prepared for</h3><p><strong>${escapeHtml(q.customer)}</strong></p>
        ${q.job_id ? `<p>Job: ${escapeHtml(q.job_id)}</p>` : ""}</div>
      <div class="right"><h3>Details</h3>
        <p>Labour: ${q.labour_hours}h @ ${money(q.labour_rate)}/h</p>
        <p>Status: <span class="status">${escapeHtml(q.status)}</span></p>
      </div>
    </div>
    <table>
      <thead><tr><th>Description</th><th class="right">Qty</th><th class="right">Unit</th><th class="right">Amount</th></tr></thead>
      <tbody>
        ${rows}
        <tr><td>Labour (${q.labour_hours}h @ ${money(q.labour_rate)}/h)</td>
            <td class="right"></td><td class="right"></td>
            <td class="right">${money(q.labour_total)}</td></tr>
      </tbody>
    </table>
    <div class="totals">
      <div class="row"><span>Materials</span><span>${money(q.materials_total)}</span></div>
      <div class="row"><span>Labour</span><span>${money(q.labour_total)}</span></div>
      <div class="row"><span>Subtotal (ex GST)</span><span>${money(q.subtotal)}</span></div>
      <div class="row"><span>GST (10%)</span><span>${money(q.gst)}</span></div>
      <div class="row grand"><span>Total</span><span>${money(q.total)}</span></div>
    </div>
    ${q.notes ? `<div class="notes"><h3>Notes</h3><p>${escapeHtml(q.notes)}</p></div>` : ""}`;
  printHtml(`Quote ${q.id}`, body);
}

// Render a stored AI summary as a clean PDF report. Supports the light markdown
// the model emits (**bold**, `code`, bullet lines, _italics_).
function summaryToHtml(text: string): string {
  const lines = text.split("\n");
  let html = "";
  let inList = false;
  const inline = (s: string) =>
    escapeHtml(s)
      .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
      .replace(/`([^`]+)`/g, "<code>$1</code>")
      .replace(/_([^_]+)_/g, "<em>$1</em>");
  for (const raw of lines) {
    const line = raw.trim();
    const bullet = line.startsWith("- ") || line.startsWith("* ");
    if (bullet) {
      if (!inList) {
        html += "<ul>";
        inList = true;
      }
      html += `<li>${inline(line.slice(2))}</li>`;
    } else {
      if (inList) {
        html += "</ul>";
        inList = false;
      }
      html += line ? `<p>${inline(line)}</p>` : "<div style='height:8px'></div>";
    }
  }
  if (inList) html += "</ul>";
  return html;
}

export function exportSummaryPdf(s: Summary): void {
  const when = new Date(s.updated_at || s.created_at).toLocaleString();
  const body = `
    <div class="head">${brand}
      <div class="doc-title"><h1>AI Report</h1><div class="ref">${escapeHtml(s.subject_ref || s.subject_type)}</div></div>
    </div>
    <div class="meta">
      <div><h3>Subject</h3><p><strong>${escapeHtml(s.title)}</strong></p>
        <p>${escapeHtml(s.subject_type)}${s.subject_ref ? ` · ${escapeHtml(s.subject_ref)}` : ""}</p></div>
      <div class="right"><h3>Generated</h3>
        <p>${escapeHtml(when)}</p>
        <p>via ${escapeHtml(s.provider)}${s.model ? ` · ${escapeHtml(s.model)}` : ""}</p>
      </div>
    </div>
    <div class="notes" style="margin-top:8px">${summaryToHtml(s.summary)}</div>`;
  printHtml(`Report — ${s.title}`, body);
}
